query OnApplicationAccept($lowerLimit: Float!, $upperLimit: Float!) {
    grantApplications(
        filter: {
            _operators: {
                updatedAtS: { gte: $lowerLimit, lte: $upperLimit }
            }
            state: "approved"
        }
    ) {
        id: _id
        applicantId
        projectName: fieldFilterBySection(filter: { field: "projectName" }) {
            values {
                value
            }
        }
        applicantName: fieldFilterBySection(filter: { field: "applicantName" }) {
            values {
                value
            }
        }
        applicantEmail: fieldFilterBySection(filter: { field: "applicantEmail" }) {
            values {
                value
            }
        }
        grant {
            id: _id
            title
            workspace {
                id: _id
                members {
                    email
                    enabled
                }
            }
        }
    }
}
