service: communication-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14

functions:
  # applicant-on-application-accept:
  #   handler: src/functions/applicant/OnApplicationAccept.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # applicant-on-application-reject:
  #   handler: src/functions/applicant/OnApplicationReject.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # applicant-on-application-resubmit:
  #   handler: src/functions/applicant/OnApplicationResubmit.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # applicant-on-application-submit:
  #   handler: src/functions/applicant/OnApplicationSubmit.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # applicant-on-asked-to-resubmit:
  #   handler: src/functions/applicant/OnAskedToResubmit.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # applicant-on-funds-received:
  #   handler: src/functions/applicant/OnFundsReceived.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # applicant-on-milestone-accept:
  #   handler: src/functions/applicant/OnMilestoneAccept.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  # dao-on-invite-members:
  #   handler: src/functions/dao/OnInviteMember.run
  #   timeout: 60
  #   reservedConcurrency: 1
  #   events:
  #     - schedule: rate(5 minutes)

  rpc-alert:
    handler: src/alerts/rpcAlert.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
