service: communication-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14

functions:
  dao-invite-members:
    handler: src/functions/dao/InviteMember.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  dao-application-received:
    handler: src/functions/dao/ApplicationReceived.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
