service: communication-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: v1
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256
  logRetentionInDays: 14

functions:

  dao-invite-members:
    handler: src/functions/dao/InviteMember.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  dao-application-received:
    handler: src/functions/dao/ApplicationReceived.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  dao-application-resubmitted:
    handler: src/functions/dao/ApplicationResubmitted.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  dao-milestone-updated:
    handler: src/functions/dao/MilestoneUpdated.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)

  applicant-applicationreject:
    handler: src/functions/applicant/ApplicationReject.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  applicant-applicationresubmit:
    handler: src/functions/applicant/ApplicationResubmit.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  applicant-applicationsubmitted:
    handler: src/functions/applicant/ApplicationSubmitted.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  applicant-funds-received:
    handler: src/functions/applicant/FundsReceived.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)
  applicant-new-grant-posted:
    handler: src/functions/applicant/NewGrantPosted.run
    timeout: 60
    reservedConcurrency: 1
    events:
      - schedule: rate(10 minutes)

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
